#pragma once
#include <string>
#include <string_view>
#include <array>
#include <vector>
#include <set>
#include <map>
#include <deque>
#include <algorithm>
#include <type_traits>
#include <compare>
#include <memory>
#include <functional>
#include <iostream>
#include <sstream>
#include <fstream>
#include <regex>
#include <cwctype>
#include <cassert>
#include <stdexcept>
#include <experimental/generator>
#include "magic_enum.hpp"
#include "StaticMap.h"
#include "Utility.h"
