#pragma once
#include <cstdint>
#include <exception>
#include <source_location>
#include <iso646.h>
#include <utility>
#include <string>
#include <string_view>
#include <array>
#include <vector>
#include <set>
#include <map>
#include <deque>
#include <algorithm>
#include <type_traits>
#include <compare>
#include <memory>
#include <functional>
#include <iostream>
#include <sstream>
#include <fstream>
#include <regex>
#include <cwctype>
#include <cassert>
#include <stdexcept>
#include <ranges>
#include "generator.hpp"
#include "Utility.h"
